[2025-03-08T17:36:32.427+0000] {processor.py:157} INFO - Started process (PID=167) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T17:36:32.429+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T17:36:32.430+0000] {logging_mixin.py:154} INFO - [2025-03-08T17:36:32.429+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T17:36:32.440+0000] {logging_mixin.py:154} INFO - [2025-03-08T17:36:32.437+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T17:36:32.440+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T17:36:32.469+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.048 seconds
[2025-03-08T17:41:42.397+0000] {processor.py:157} INFO - Started process (PID=172) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T17:41:42.397+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T17:41:42.398+0000] {logging_mixin.py:154} INFO - [2025-03-08T17:41:42.397+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T17:41:42.400+0000] {logging_mixin.py:154} INFO - [2025-03-08T17:41:42.400+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T17:41:42.401+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T17:41:42.412+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.018 seconds
[2025-03-08T17:50:08.116+0000] {processor.py:157} INFO - Started process (PID=180) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T17:50:08.118+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T17:50:08.123+0000] {logging_mixin.py:154} INFO - [2025-03-08T17:50:08.120+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T17:50:08.147+0000] {logging_mixin.py:154} INFO - [2025-03-08T17:50:08.144+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T17:50:08.148+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T17:50:08.212+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.101 seconds
[2025-03-08T17:55:45.268+0000] {processor.py:157} INFO - Started process (PID=188) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T17:55:45.269+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T17:55:45.270+0000] {logging_mixin.py:154} INFO - [2025-03-08T17:55:45.270+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T17:55:45.287+0000] {logging_mixin.py:154} INFO - [2025-03-08T17:55:45.282+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T17:55:45.288+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T17:55:45.324+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.064 seconds
[2025-03-08T18:01:17.423+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:01:17.426+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:01:17.428+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:01:17.427+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:01:17.444+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:01:17.440+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:01:17.445+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:01:17.490+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.073 seconds
[2025-03-08T18:07:36.127+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:07:36.128+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:07:36.129+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:07:36.128+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:07:36.137+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:07:36.135+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:07:36.137+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:07:36.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.033 seconds
[2025-03-08T18:13:13.824+0000] {processor.py:157} INFO - Started process (PID=205) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:13:13.825+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:13:13.826+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:13:13.826+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:13:13.849+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:13:13.842+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:13:13.849+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:13:13.916+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.099 seconds
[2025-03-08T18:23:49.646+0000] {processor.py:157} INFO - Started process (PID=210) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:23:49.648+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:23:49.651+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:23:49.650+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:23:49.668+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:23:49.664+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:23:49.668+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:23:49.717+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.084 seconds
[2025-03-08T18:30:55.851+0000] {processor.py:157} INFO - Started process (PID=217) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:30:55.852+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:30:55.854+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:30:55.853+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:30:55.872+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:30:55.867+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:30:55.873+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:30:55.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.079 seconds
[2025-03-08T18:31:26.342+0000] {processor.py:157} INFO - Started process (PID=222) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:31:26.344+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:31:26.346+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:31:26.345+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:31:26.360+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:31:26.359+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:31:26.361+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:31:26.390+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.062 seconds
[2025-03-08T18:32:03.368+0000] {processor.py:157} INFO - Started process (PID=227) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:32:03.370+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:32:03.371+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:32:03.370+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:32:03.378+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:32:03.377+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:32:03.379+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:32:03.399+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.042 seconds
[2025-03-08T18:32:33.976+0000] {processor.py:157} INFO - Started process (PID=232) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:32:33.977+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:32:33.978+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:32:33.978+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:32:33.988+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:32:33.986+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:32:33.988+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:32:34.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.042 seconds
[2025-03-08T18:33:11.743+0000] {processor.py:157} INFO - Started process (PID=237) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:33:11.745+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:33:11.746+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:33:11.745+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:33:11.752+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:33:11.750+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:33:11.752+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:33:11.775+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.037 seconds
[2025-03-08T18:39:47.774+0000] {processor.py:157} INFO - Started process (PID=242) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:39:47.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:39:47.776+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:39:47.776+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:39:47.791+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:39:47.786+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:39:47.791+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:39:47.841+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.073 seconds
[2025-03-08T18:45:18.373+0000] {processor.py:157} INFO - Started process (PID=247) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:45:18.375+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:45:18.376+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:45:18.376+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:45:18.391+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:45:18.387+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:45:18.392+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:45:18.437+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.082 seconds
[2025-03-08T18:46:10.911+0000] {processor.py:157} INFO - Started process (PID=252) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:46:10.917+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:46:10.977+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:46:10.975+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:46:10.996+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:46:10.992+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:46:10.997+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:46:11.037+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.161 seconds
[2025-03-08T18:46:42.041+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:46:42.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:46:42.045+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:46:42.044+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:46:42.053+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:46:42.051+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:46:42.053+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:46:42.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.043 seconds
[2025-03-08T18:47:12.352+0000] {processor.py:157} INFO - Started process (PID=264) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:47:12.353+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:47:12.354+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:47:12.354+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:47:12.358+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:47:12.357+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:47:12.358+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:47:12.378+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.028 seconds
[2025-03-08T18:47:42.681+0000] {processor.py:157} INFO - Started process (PID=269) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:47:42.682+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:47:42.683+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:47:42.683+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:47:42.688+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:47:42.687+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:47:42.688+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:47:42.703+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.027 seconds
[2025-03-08T18:48:12.988+0000] {processor.py:157} INFO - Started process (PID=274) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:48:12.989+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:48:12.990+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:48:12.990+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:48:12.997+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:48:12.995+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:48:12.997+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:48:13.017+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.035 seconds
[2025-03-08T18:48:43.337+0000] {processor.py:157} INFO - Started process (PID=279) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:48:43.339+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:48:43.340+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:48:43.340+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:48:43.346+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:48:43.345+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:48:43.346+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:48:43.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.031 seconds
[2025-03-08T18:49:13.683+0000] {processor.py:157} INFO - Started process (PID=284) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:49:13.684+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:49:13.685+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:49:13.685+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:49:13.693+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:49:13.692+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:49:13.693+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:49:13.710+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.033 seconds
[2025-03-08T18:49:44.046+0000] {processor.py:157} INFO - Started process (PID=289) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:49:44.047+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:49:44.048+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:49:44.048+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:49:44.053+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:49:44.052+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:49:44.053+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:49:44.068+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.027 seconds
[2025-03-08T18:50:14.381+0000] {processor.py:157} INFO - Started process (PID=294) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:50:14.382+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:50:14.383+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:50:14.382+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:50:14.389+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:50:14.388+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:50:14.389+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:50:14.404+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.027 seconds
[2025-03-08T18:50:44.748+0000] {processor.py:157} INFO - Started process (PID=299) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:50:44.749+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:50:44.750+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:50:44.749+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:50:44.755+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:50:44.754+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:50:44.756+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:50:44.773+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.029 seconds
[2025-03-08T18:51:15.149+0000] {processor.py:157} INFO - Started process (PID=304) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:51:15.150+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:51:15.151+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:51:15.151+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:51:15.160+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:51:15.158+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:51:15.161+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:51:15.182+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.037 seconds
[2025-03-08T18:51:45.493+0000] {processor.py:157} INFO - Started process (PID=309) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:51:45.496+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:51:45.497+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:51:45.496+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:51:45.503+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:51:45.502+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:51:45.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:51:45.524+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.035 seconds
[2025-03-08T18:52:15.817+0000] {processor.py:157} INFO - Started process (PID=314) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:52:15.818+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:52:15.819+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:52:15.819+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:52:15.824+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:52:15.823+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'extractor'
[2025-03-08T18:52:15.824+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:52:15.840+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.026 seconds
[2025-03-08T18:52:41.064+0000] {processor.py:157} INFO - Started process (PID=319) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:52:41.065+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:52:41.065+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:52:41.065+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:52:41.076+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:52:41.075+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T18:52:41.076+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:52:41.093+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.033 seconds
[2025-03-08T18:53:11.340+0000] {processor.py:157} INFO - Started process (PID=324) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:53:11.341+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:53:11.342+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:53:11.341+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:53:11.346+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:53:11.345+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T18:53:11.347+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:53:11.361+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.024 seconds
[2025-03-08T18:53:41.594+0000] {processor.py:157} INFO - Started process (PID=329) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:53:41.596+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:53:41.597+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:53:41.597+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:53:41.606+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:53:41.604+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T18:53:41.606+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:53:41.629+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.040 seconds
[2025-03-08T18:54:11.910+0000] {processor.py:157} INFO - Started process (PID=334) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:54:11.911+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:54:11.912+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:54:11.912+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:54:11.917+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:54:11.916+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T18:54:11.917+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:54:11.933+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.026 seconds
[2025-03-08T18:54:42.268+0000] {processor.py:157} INFO - Started process (PID=339) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:54:42.269+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:54:42.270+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:54:42.270+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:54:42.282+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:54:42.280+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T18:54:42.282+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:54:42.306+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.044 seconds
[2025-03-08T18:55:12.576+0000] {processor.py:157} INFO - Started process (PID=344) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:55:12.577+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:55:12.578+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:55:12.578+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:55:12.583+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:55:12.582+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T18:55:12.584+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:55:12.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.030 seconds
[2025-03-08T18:55:42.919+0000] {processor.py:157} INFO - Started process (PID=349) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:55:42.921+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T18:55:42.921+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:55:42.921+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:55:42.927+0000] {logging_mixin.py:154} INFO - [2025-03-08T18:55:42.926+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T18:55:42.927+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T18:55:42.944+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.029 seconds
[2025-03-08T19:00:26.492+0000] {processor.py:157} INFO - Started process (PID=356) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:00:26.493+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:00:26.494+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:00:26.494+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:00:26.505+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:00:26.503+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:00:26.506+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:00:26.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.058 seconds
[2025-03-08T19:01:12.631+0000] {processor.py:157} INFO - Started process (PID=361) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:01:12.633+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:01:12.633+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:01:12.633+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:01:12.638+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:01:12.637+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:01:12.639+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:01:12.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.028 seconds
[2025-03-08T19:01:56.163+0000] {processor.py:157} INFO - Started process (PID=366) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:01:56.164+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:01:56.165+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:01:56.164+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:01:56.170+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:01:56.169+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:01:56.170+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:01:56.184+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.024 seconds
[2025-03-08T19:02:56.165+0000] {processor.py:157} INFO - Started process (PID=373) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:02:56.166+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:02:56.167+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:02:56.167+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:02:56.173+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:02:56.172+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:02:56.173+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:02:56.189+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.027 seconds
[2025-03-08T19:03:33.073+0000] {processor.py:157} INFO - Started process (PID=378) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:03:33.074+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:03:33.075+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:03:33.075+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:03:33.082+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:03:33.081+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:03:33.082+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:03:33.102+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.033 seconds
[2025-03-08T19:06:01.815+0000] {processor.py:157} INFO - Started process (PID=383) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:06:01.817+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:06:01.818+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:06:01.817+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:06:01.826+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:06:01.824+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:06:01.826+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:06:01.846+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.033 seconds
[2025-03-08T19:06:39.024+0000] {processor.py:157} INFO - Started process (PID=388) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:06:39.025+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:06:39.026+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:06:39.026+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:06:39.035+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:06:39.033+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:06:39.035+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:06:39.054+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.035 seconds
[2025-03-08T19:10:00.833+0000] {processor.py:157} INFO - Started process (PID=395) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:10:00.836+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:10:00.837+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:10:00.837+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:10:00.847+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:10:00.844+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:10:00.847+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:10:00.874+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.043 seconds
[2025-03-08T19:20:33.397+0000] {processor.py:157} INFO - Started process (PID=400) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:20:33.397+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:20:33.398+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:20:33.398+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:20:33.404+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:20:33.402+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:20:33.404+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:20:33.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.026 seconds
[2025-03-08T19:38:27.056+0000] {processor.py:157} INFO - Started process (PID=405) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:38:27.057+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:38:27.058+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:38:27.057+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:38:27.064+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:38:27.063+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:38:27.064+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:38:27.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.025 seconds
[2025-03-08T19:42:09.532+0000] {processor.py:157} INFO - Started process (PID=411) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:42:09.535+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:42:09.536+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:42:09.536+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:42:09.547+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:42:09.544+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:42:09.548+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:42:09.579+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.052 seconds
[2025-03-08T19:42:41.888+0000] {processor.py:157} INFO - Started process (PID=417) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:42:41.889+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:42:41.890+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:42:41.890+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:42:41.898+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:42:41.896+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:42:41.898+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:42:41.918+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.034 seconds
[2025-03-08T19:48:11.910+0000] {processor.py:157} INFO - Started process (PID=422) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:48:11.912+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:48:11.913+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:48:11.912+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:48:11.918+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:48:11.917+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:48:11.918+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:48:11.936+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.032 seconds
[2025-03-08T19:56:02.004+0000] {processor.py:157} INFO - Started process (PID=429) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:56:02.005+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T19:56:02.006+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:56:02.006+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:56:02.015+0000] {logging_mixin.py:154} INFO - [2025-03-08T19:56:02.013+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T19:56:02.016+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T19:56:02.050+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.051 seconds
[2025-03-08T20:01:38.097+0000] {processor.py:157} INFO - Started process (PID=434) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:01:38.098+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T20:01:38.099+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:01:38.099+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:01:38.105+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:01:38.103+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T20:01:38.105+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:01:38.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.025 seconds
[2025-03-08T20:18:10.296+0000] {processor.py:157} INFO - Started process (PID=439) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:18:10.298+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T20:18:10.303+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:18:10.303+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:18:10.316+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:18:10.314+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T20:18:10.317+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:18:10.349+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.058 seconds
[2025-03-08T20:20:19.015+0000] {processor.py:157} INFO - Started process (PID=444) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:20:19.017+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T20:20:19.018+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:20:19.018+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:20:19.024+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:20:19.023+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T20:20:19.024+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:20:19.045+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.035 seconds
[2025-03-08T20:27:16.806+0000] {processor.py:157} INFO - Started process (PID=451) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:27:16.809+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T20:27:16.811+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:27:16.810+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:27:16.827+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:27:16.823+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T20:27:16.827+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:27:16.867+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.068 seconds
[2025-03-08T20:32:48.975+0000] {processor.py:157} INFO - Started process (PID=456) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:32:48.976+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T20:32:48.976+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:32:48.976+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:32:48.981+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:32:48.980+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T20:32:48.981+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:32:48.996+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.024 seconds
[2025-03-08T20:38:23.238+0000] {processor.py:157} INFO - Started process (PID=461) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:38:23.240+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T20:38:23.242+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:38:23.241+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:38:23.254+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:38:23.251+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T20:38:23.255+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:38:23.292+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.059 seconds
[2025-03-08T20:47:23.339+0000] {processor.py:157} INFO - Started process (PID=466) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:47:23.340+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T20:47:23.341+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:47:23.341+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:47:23.349+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:47:23.347+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T20:47:23.350+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:47:23.377+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.042 seconds
[2025-03-08T20:52:55.493+0000] {processor.py:157} INFO - Started process (PID=471) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:52:55.495+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T20:52:55.496+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:52:55.496+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:52:55.508+0000] {logging_mixin.py:154} INFO - [2025-03-08T20:52:55.505+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T20:52:55.509+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T20:52:55.541+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.055 seconds
[2025-03-08T21:02:24.283+0000] {processor.py:157} INFO - Started process (PID=476) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:02:24.284+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T21:02:24.285+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:02:24.285+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:02:24.293+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:02:24.291+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T21:02:24.293+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:02:24.319+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.041 seconds
[2025-03-08T21:07:58.078+0000] {processor.py:157} INFO - Started process (PID=482) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:07:58.080+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T21:07:58.081+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:07:58.080+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:07:58.088+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:07:58.087+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T21:07:58.089+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:07:58.116+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.042 seconds
[2025-03-08T21:22:58.931+0000] {processor.py:157} INFO - Started process (PID=488) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:22:58.934+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T21:22:58.936+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:22:58.935+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:22:58.952+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:22:58.949+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T21:22:58.953+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:22:58.992+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.064 seconds
[2025-03-08T21:28:34.158+0000] {processor.py:157} INFO - Started process (PID=495) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:28:34.162+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T21:28:34.163+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:28:34.163+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:28:34.205+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:28:34.198+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T21:28:34.205+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:28:34.230+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.078 seconds
[2025-03-08T21:34:09.053+0000] {processor.py:157} INFO - Started process (PID=500) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:34:09.054+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T21:34:09.055+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:34:09.054+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:34:09.059+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:34:09.058+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T21:34:09.060+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:34:09.075+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.025 seconds
[2025-03-08T21:39:41.939+0000] {processor.py:157} INFO - Started process (PID=505) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:39:41.940+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T21:39:41.941+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:39:41.941+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:39:41.946+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:39:41.945+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T21:39:41.946+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:39:41.961+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.025 seconds
[2025-03-08T21:45:15.287+0000] {processor.py:157} INFO - Started process (PID=511) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:45:15.288+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T21:45:15.288+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:45:15.288+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:45:15.296+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:45:15.294+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T21:45:15.297+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:45:15.617+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.332 seconds
[2025-03-08T21:55:56.506+0000] {processor.py:157} INFO - Started process (PID=516) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:55:56.506+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T21:55:56.507+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:55:56.507+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:55:56.513+0000] {logging_mixin.py:154} INFO - [2025-03-08T21:55:56.512+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T21:55:56.513+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T21:55:56.528+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.025 seconds
[2025-03-08T22:01:31.709+0000] {processor.py:157} INFO - Started process (PID=522) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:01:31.709+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T22:01:31.710+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:01:31.710+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:01:31.715+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:01:31.714+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T22:01:31.715+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:01:31.728+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.022 seconds
[2025-03-08T22:07:08.013+0000] {processor.py:157} INFO - Started process (PID=528) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:07:08.014+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T22:07:08.015+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:07:08.015+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:07:08.022+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:07:08.021+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T22:07:08.023+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:07:08.048+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.038 seconds
[2025-03-08T22:12:40.208+0000] {processor.py:157} INFO - Started process (PID=533) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:12:40.209+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T22:12:40.210+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:12:40.209+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:12:40.215+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:12:40.214+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T22:12:40.215+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:12:40.235+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.030 seconds
[2025-03-08T22:33:46.972+0000] {processor.py:157} INFO - Started process (PID=538) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:33:46.973+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T22:33:46.974+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:33:46.973+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:33:46.980+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:33:46.978+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T22:33:46.980+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:33:47.002+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.034 seconds
[2025-03-08T22:34:17.323+0000] {processor.py:157} INFO - Started process (PID=543) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:34:17.323+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T22:34:17.324+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:34:17.324+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:34:17.329+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:34:17.328+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T22:34:17.329+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:34:17.345+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.025 seconds
[2025-03-08T22:39:48.888+0000] {processor.py:157} INFO - Started process (PID=549) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:39:48.889+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T22:39:48.891+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:39:48.890+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:39:48.904+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:39:48.901+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T22:39:48.905+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:39:48.946+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.064 seconds
[2025-03-08T22:50:25.435+0000] {processor.py:157} INFO - Started process (PID=555) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:50:25.436+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T22:50:25.437+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:50:25.437+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:50:25.447+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:50:25.442+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T22:50:25.447+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:50:25.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.044 seconds
[2025-03-08T22:55:59.156+0000] {processor.py:157} INFO - Started process (PID=560) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:55:59.157+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T22:55:59.158+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:55:59.157+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:55:59.169+0000] {logging_mixin.py:154} INFO - [2025-03-08T22:55:59.167+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T22:55:59.169+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T22:55:59.192+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.039 seconds
[2025-03-08T23:01:31.666+0000] {processor.py:157} INFO - Started process (PID=567) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:01:31.667+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T23:01:31.668+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:01:31.668+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:01:31.676+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:01:31.675+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T23:01:31.676+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:01:31.689+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.027 seconds
[2025-03-08T23:12:03.938+0000] {processor.py:157} INFO - Started process (PID=572) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:12:03.939+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T23:12:03.940+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:12:03.939+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:12:03.947+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:12:03.945+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T23:12:03.947+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:12:03.973+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.038 seconds
[2025-03-08T23:17:36.510+0000] {processor.py:157} INFO - Started process (PID=579) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:17:36.511+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T23:17:36.512+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:17:36.512+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:17:36.520+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:17:36.518+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T23:17:36.520+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:17:36.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.039 seconds
[2025-03-08T23:23:07.710+0000] {processor.py:157} INFO - Started process (PID=584) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:23:07.711+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T23:23:07.712+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:23:07.711+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:23:07.719+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:23:07.718+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T23:23:07.720+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:23:07.741+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.035 seconds
[2025-03-08T23:28:38.180+0000] {processor.py:157} INFO - Started process (PID=589) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:28:38.181+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T23:28:38.182+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:28:38.181+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:28:38.186+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:28:38.185+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T23:28:38.187+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:28:38.201+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.023 seconds
[2025-03-08T23:39:14.668+0000] {processor.py:157} INFO - Started process (PID=594) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:39:14.670+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T23:39:14.671+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:39:14.670+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:39:14.677+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:39:14.676+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T23:39:14.678+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:39:14.701+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.036 seconds
[2025-03-08T23:44:49.875+0000] {processor.py:157} INFO - Started process (PID=600) to work on /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:44:49.876+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/news_etl_dag.py for tasks to queue
[2025-03-08T23:44:49.877+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:44:49.876+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:44:49.880+0000] {logging_mixin.py:154} INFO - [2025-03-08T23:44:49.879+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/news_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/news_etl_dag.py", line 16, in <module>
    from etl.extractor.api_extractor import ScienceNewsExtractor, CryptoMarketExtractor
ModuleNotFoundError: No module named 'etl'
[2025-03-08T23:44:49.880+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/news_etl_dag.py
[2025-03-08T23:44:49.892+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/news_etl_dag.py took 0.018 seconds
